# Generated by Django 6.1.1 on 2026-09-17 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_expense_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_dropped", models.IntegerField()),
                ("drop_off_date", models.DateField(auto_now_add=True)),
                ("quantity_sold", models.IntegerField(default=0)),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("settlement_date", models.DateField(blank=True, null=True)),
                ("is_settled", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
    ]
